name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AKIAW3W3RITTHS2NDSZT }}
          aws-secret-access-key: ${{ secrets.VgGXndILyaEIWth/SKJRDmzyNXC9Pkc4eVr8Vj8s }}
          aws-region: ap-northeast-2

      - name: Deploy
        run: |
          aws s3 cp index.html s3://github-actions-deploy-cha